// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProduct(ctx context.Context, id int64) error
	DeleteStore(ctx context.Context, id int64) error
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetProductForUpdate(ctx context.Context, id int64) (Product, error)
	GetStore(ctx context.Context, id int64) (Store, error)
	GetStoreForUpdate(ctx context.Context, id int64) (Store, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListProducts(ctx context.Context, storeID int64) ([]Product, error)
	ListStores(ctx context.Context, owner string) ([]Store, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error)
}

var _ Querier = (*Queries)(nil)
